packages:
  - packages/**
  - examples/**
  - "!**/.next/**"
  - "!**/dist/**"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - lmdb
  - msgpackr-extract
  - nice-napi
  - sharp
  - svelte-preprocess
