name: 🚀 New feature proposal
description: Propose a new feature to be added to Zoom Image
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report :)
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the problem
      description: "As a developer using Zoom Image I want [goal / wish] so that [benefit]"
    validations:
      required: true
